name             'php'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures php'
long_description 'Installs/Configures php'
version          '2.3.23'

depends 'apt'
depends 'cron'